/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cineotaku.proyecto_cine.vista;

import com.cineotaku.proyecto_cine.controlador.*;
import com.cineotaku.proyecto_cine.modelo.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 *
 * @author User
 */
public class UbicacionAsientos extends javax.swing.JFrame {
    
    // Variables de negocio
    private CineControlador controlador;
    private Funcion funcion;
    private Pelicula pelicula;
    private JButton[][] botonesAsientos;
    private java.util.List<Butaca> asientosSeleccionados;

    /**
     * Creates new form UbicacionAsientos
     */
    public UbicacionAsientos() {
        initComponents();
    }
    
    public UbicacionAsientos(CineControlador controlador, Funcion funcion, Pelicula pelicula) {
        this.controlador = controlador;
        this.funcion = funcion;
        this.pelicula = pelicula;
        this.asientosSeleccionados = new java.util.ArrayList<>();
        initComponents();
        setupCustomComponents();
        cargarAsientos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panelInfo = new javax.swing.JPanel();
        lblPelicula = new javax.swing.JLabel();
        lblFuncion = new javax.swing.JLabel();
        lblInstrucciones = new javax.swing.JLabel();
        panelCentral = new javax.swing.JPanel();
        lblPantalla = new javax.swing.JLabel();
        panelAsientos = new javax.swing.JPanel();
        panelLeyenda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnDisponible = new javax.swing.JButton();
        btnOcupado = new javax.swing.JButton();
        btnSeleccionado = new javax.swing.JButton();
        panelInferior = new javax.swing.JPanel();
        panelResumen = new javax.swing.JPanel();
        lblSeleccionados = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selección de Asientos");
        setPreferredSize(new java.awt.Dimension(900, 700));

        panelInfo.setBackground(new java.awt.Color(25, 25, 112));
        panelInfo.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20));
        panelInfo.setLayout(new java.awt.GridLayout(3, 1, 5, 5));

        lblPelicula.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lblPelicula.setText("Película");
        panelInfo.add(lblPelicula);

        lblFuncion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblFuncion.setForeground(new java.awt.Color(255, 255, 255));
        lblFuncion.setText("Función");
        panelInfo.add(lblFuncion);

        lblInstrucciones.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        lblInstrucciones.setForeground(new java.awt.Color(255, 255, 0));
        lblInstrucciones.setText("Seleccione sus asientos (máximo 8 por compra)");
        panelInfo.add(lblInstrucciones);

        panelCentral.setLayout(new java.awt.BorderLayout());

        lblPantalla.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblPantalla.setForeground(new java.awt.Color(51, 51, 51));
        lblPantalla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPantalla.setText("PANTALLA");
        lblPantalla.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2), javax.swing.BorderFactory.createEmptyBorder(10, 0, 10, 0)));
        panelCentral.add(lblPantalla, java.awt.BorderLayout.PAGE_START);

        panelAsientos.setBackground(new java.awt.Color(240, 248, 255));
        panelAsientos.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 50, 20, 50));
        panelAsientos.setLayout(new java.awt.GridLayout(5, 4, 5, 5));
        panelCentral.add(panelAsientos, java.awt.BorderLayout.CENTER);

        panelLeyenda.setBackground(new java.awt.Color(240, 248, 255));
        panelLeyenda.setLayout(new java.awt.FlowLayout());

        jLabel1.setText("Leyenda: ");
        panelLeyenda.add(jLabel1);

        btnDisponible.setBackground(new java.awt.Color(40, 167, 69));
        btnDisponible.setForeground(new java.awt.Color(255, 255, 255));
        btnDisponible.setText("Disponible");
        btnDisponible.setEnabled(false);
        panelLeyenda.add(btnDisponible);

        btnOcupado.setBackground(new java.awt.Color(220, 53, 69));
        btnOcupado.setForeground(new java.awt.Color(255, 255, 255));
        btnOcupado.setText("Ocupado");
        btnOcupado.setEnabled(false);
        panelLeyenda.add(btnOcupado);

        btnSeleccionado.setBackground(new java.awt.Color(255, 193, 7));
        btnSeleccionado.setForeground(new java.awt.Color(0, 0, 0));
        btnSeleccionado.setText("Seleccionado");
        btnSeleccionado.setEnabled(false);
        panelLeyenda.add(btnSeleccionado);

        panelCentral.add(panelLeyenda, java.awt.BorderLayout.PAGE_END);

        panelInferior.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20));
        panelInferior.setLayout(new java.awt.BorderLayout());

        panelResumen.setLayout(new java.awt.GridLayout(2, 1, 5, 5));

        lblSeleccionados.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSeleccionados.setText("Asientos seleccionados: Ninguno");
        panelResumen.add(lblSeleccionados);

        lblTotal.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 128, 0));
        lblTotal.setText("Total: $0.00");
        panelResumen.add(lblTotal);

        panelInferior.add(panelResumen, java.awt.BorderLayout.LINE_START);

        panelBotones.setLayout(new java.awt.FlowLayout());

        btnVolver.setBackground(new java.awt.Color(108, 117, 125));
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("← Volver");
        btnVolver.setBorderPainted(false);
        btnVolver.setFocusPainted(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        panelBotones.add(btnVolver);

        btnContinuar.setBackground(new java.awt.Color(40, 167, 69));
        btnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuar.setText("Continuar →");
        btnContinuar.setBorderPainted(false);
        btnContinuar.setEnabled(false);
        btnContinuar.setFocusPainted(false);
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        panelBotones.add(btnContinuar);

        panelInferior.add(panelBotones, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
            .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {                                          
        dispose();
    }                                         

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        continuarCompra();
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UbicacionAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UbicacionAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UbicacionAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UbicacionAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UbicacionAsientos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnDisponible;
    private javax.swing.JButton btnOcupado;
    private javax.swing.JButton btnSeleccionado;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFuncion;
    private javax.swing.JLabel lblInstrucciones;
    private javax.swing.JLabel lblPantalla;
    private javax.swing.JLabel lblPelicula;
    private javax.swing.JLabel lblSeleccionados;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panelAsientos;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelLeyenda;
    private javax.swing.JPanel panelResumen;
    // End of variables declaration                   
    
    // Métodos personalizados
    private void setupCustomComponents() {
        if (pelicula != null) {
            setTitle("Selección de Asientos - " + pelicula.getTitulo());
            lblPelicula.setText(pelicula.getTitulo());
        }
        
        if (funcion != null && controlador != null) {
            Sala sala = controlador.getSalaControlador().obtenerPorId(funcion.getSalaId());
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
            lblFuncion.setText(funcion.getFechaHora().format(formatter) + 
                             " - Sala: " + (sala != null ? sala.getNombre() : "Sala " + funcion.getSalaId()));
        }
    }
    
    private void cargarAsientos() {
        if (controlador == null || funcion == null) return;
        
        panelAsientos.removeAll();
        List<Butaca> butacas = controlador.getSalaControlador().obtenerButacasPorSala(funcion.getSalaId());
        
        // Crear matriz de botones para los asientos (5 filas A-E, 4 columnas 1-4)
        botonesAsientos = new JButton[5][4];
        char[] filas = {'A', 'B', 'C', 'D', 'E'};
        
        for (int fila = 0; fila < 5; fila++) {
            for (int columna = 0; columna < 4; columna++) {
                final char letraFila = filas[fila];
                final int numeroColumna = columna + 1;
                
                Butaca butaca = obtenerButaca(butacas, letraFila, numeroColumna);
                
                JButton btnAsiento = new JButton(letraFila + String.valueOf(numeroColumna));
                btnAsiento.setFont(new Font("Arial", Font.BOLD, 12));
                btnAsiento.setFocusPainted(false);
                btnAsiento.setBorderPainted(false);
                btnAsiento.setPreferredSize(new Dimension(80, 60));
                
                if (butaca != null) {
                    if (butaca.isOcupada() || butaca.isReservada()) {
                        btnAsiento.setBackground(new Color(220, 53, 69));
                        btnAsiento.setForeground(Color.WHITE);
                        btnAsiento.setEnabled(false);
                    } else {
                        btnAsiento.setBackground(new Color(40, 167, 69));
                        btnAsiento.setForeground(Color.WHITE);
                        btnAsiento.addActionListener(e -> toggleAsiento(butaca, btnAsiento));
                    }
                } else {
                    btnAsiento.setBackground(Color.LIGHT_GRAY);
                    btnAsiento.setEnabled(false);
                }
                
                botonesAsientos[fila][columna] = btnAsiento;
                panelAsientos.add(btnAsiento);
            }
        }
        
        panelAsientos.revalidate();
        panelAsientos.repaint();
    }
    
    private Butaca obtenerButaca(List<Butaca> butacas, char fila, int numero) {
        return butacas.stream()
                .filter(b -> b.getFila() == fila && b.getNumero() == numero)
                .findFirst()
                .orElse(null);
    }
    
    private void toggleAsiento(Butaca butaca, JButton boton) {
        if (asientosSeleccionados.contains(butaca)) {
            // Deseleccionar
            asientosSeleccionados.remove(butaca);
            boton.setBackground(new Color(40, 167, 69));
            boton.setForeground(Color.WHITE);
        } else {
            // Seleccionar (máximo 8)
            if (asientosSeleccionados.size() < 8) {
                asientosSeleccionados.add(butaca);
                boton.setBackground(new Color(255, 193, 7));
                boton.setForeground(Color.BLACK);
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Máximo 8 asientos por compra", 
                    "Límite alcanzado", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        
        actualizarResumen();
    }
    
    private void actualizarResumen() {
        if (asientosSeleccionados.isEmpty()) {
            lblSeleccionados.setText("Asientos seleccionados: Ninguno");
            lblTotal.setText("Total: $0.00");
            btnContinuar.setEnabled(false);
        } else {
            StringBuilder sb = new StringBuilder("Asientos seleccionados: ");
            for (int i = 0; i < asientosSeleccionados.size(); i++) {
                if (i > 0) sb.append(", ");
                sb.append(asientosSeleccionados.get(i).toString());
            }
            lblSeleccionados.setText(sb.toString());
            
            if (funcion != null) {
                double total = asientosSeleccionados.size() * funcion.getPrecio();
                lblTotal.setText("Total: $" + String.format("%.2f", total));
            }
            btnContinuar.setEnabled(true);
        }
    }
    
    private void continuarCompra() {
        if (controlador != null && funcion != null && pelicula != null && !asientosSeleccionados.isEmpty()) {
            new Pagos(controlador, funcion, pelicula, asientosSeleccionados).setVisible(true);
            dispose();
        }
    }
}